### ISSUE TITLE
how to add bone/joint for Custom model?

### ISSUE THREAD

**Issue by yy10112002** [jtydhr88/sd-3dmodel-loader#64]
Can anyone kindly tell me how to add bone/joint for custom model?

**Comment by jtydhr88** [comment]
As the author, i am sorry but I don’t implement the feature to add bones/joint to custom models.
Adding bones to objects is an advanced feature for 3d modeling software, because it requires many different aspects, such as the bones chain FK/IK, skinning, and so on.
This extension may not have chance to implement such complicate features

**Comment by jtydhr88** [comment]
But thanks for the feedback, I would like to close this issue for now
